### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by NathanBnm** [fleury08/prettifier#15]
Please add translations in `po` directory for the app to be translated. I can translate it to French. Don't forget to add `data` strings like `appdata.xml` and `desktop`.

**Comment by NathanBnm** [comment]
I just opened #17. Please check your files but as your app is in English by default you don't have to create an 'en.po' file.

**Comment by fleury08** [comment]
Closing this issue, version with french was published and sent to appcenter.
