### ISSUE TITLE
JSON screenshot doesn't exist

### ISSUE THREAD

**Issue by donadigo** [fleury08/prettifier#9]
I've accepted to release 1.0.5 version of Prettifier to AppCenter but reporting here for your information. The URL https://github.com/fleury08/prettifier/raw/master/data/images/PrettifierJSON.png doesn't work so it won't be actually visible in AppCenter. Rename the file in your repo from `PrettifierJson.png` to `PrettifierJSON.png` so that the screenshot can be shown.

**Comment by fleury08** [comment]
Solved https://github.com/fleury08/prettifier/commit/919c4fa995a1098f629342bd4b35b89435b531fe
